title: Product
num: zero

status:
  draft: true
  listed: true

columns:
  main:
    width: 2/3
    sections:
      content:
        type: fields
        fields:
          short_description:
            label: Korte beschrijving
            type: text
          Description:
            label: Beschrijving
            type: textarea
          pre-reqs:
            label: Van te voren nodig
            type: structure
            fields:
              required:
                label: Benodigdheden
                type: text
          price:
            type: structure
            label: Prijs
            before: €
            fields:
              name:
                label: Naam
                type: text
              price:
                label: Prijs
                type: text
          difficulty:
            type: range
            label: Moeilijkheid
            step: 1
            min: 1
            max: 5
            tooltip:
              before: ★
          time:
            type: number
            label: Tijd
            min: 1
            after: Minuten
          link:
            label: Website
            type: url
          company_tags:
            label: Bedrijf tags
            type: multiselect
            fetch: site.tags_company
            options: query
            query: site.find("tags").tags_company().split
          product_tags:
            label: Product tags
            type: multiselect
            fetch: site.tags_product
            options: query
            query: site.find("tags").tags_product().split

  sidebar:
    width: 1/3
    sections:
      logo:
        extends: sections/image
        template: cover
        max: 1
      cover:
        label: Cover Image
        type: files
        options: images







