title: Product
preset: page
num: zero

status:
  draft: true
  listed: true

fields:
  price:
    type: number
    step: 0.01
    before: €
  tags:
    label: Tags
    type: multiselect
    fetch: site.tags
    options: query
    query: site.pages.unlisted.tags.

  link:
    type: url
  description:
    type: textarea

sidebar:
  image:
    extends: sections/image
    template: cover
    min: 1
    image:
      ratio: 1/1