type: pages
headline: Products
parent: site.find("shop")
template: product
info: " {{ page.short_description }} {{ page.link }}"
image:
  query: page.images.template("single-image").first
  ratio: 1/1
  back: pattern