title: Site


columns:
    - width: 2/3
      sections:
        pages:
          type: pages

  # The second column has two sections, `notes` and `pages`
  - width: 1/3
      sections:
        files:
          type: files



